### PR TITLE
fix transition properties with Firefox

### LINKED ISSUE #17: Incorrect transitionEnd event name reported in Firefox
dom-helpers currently report `mozTransitionEnd` as the event name for  Firefox, which is not implemented anymore in Firefox. Instead the standard `transitionend` should be used.

### PR DESCRIPTION
**Pull request by oliviertassinari**
Closes #17.
Closes #18.

### CODE REVIEW

File: src/transition/properties.js [hunk 1]
```diff
@@ -52,7 +52,7 @@ function getTransitionProperties() {
 
   let vendorMap = {
     O: e => `o${e.toLowerCase()}`,
-    Moz: e => `moz${e}`,
```
Comment (oliviertassinari) [inline src/transition/properties.js]: The logic used to be
```js
let eventNames = {
  O:      'otransitionend',
  Moz:    'transitionend',
  Webkit: 'webkitTransitionEnd',
  ms:     'MSTransitionEnd'
```

File: src/transition/properties.js [hunk 2]
```diff
@@ -52,7 +52,7 @@ function getTransitionProperties() {
...
+    Moz: e => e.toLowerCase(),
```
Comment (jquense) [inline src/transition/properties.js]: this isn't right. These are specifically the vendor prefixed  property names

Comment (oliviertassinari) [inline src/transition/properties.js]: I can't find any reference to `mozTransitionEnd`.
For instance
> FWIW, mozTransitionEnd has never been implemented in Firefox. The lowercase (per spec) transitionend is required.
https://github.com/madrobby/zepto/pull/742#issuecomment-26948989

Comment (jquense) [inline src/transition/properties.js]: yes, we changed the logic to better match what React does. which has a more generic "vendor prefix any event" utility. Doing more research tho you're right, that bites us here where there isn't actually a prefixed firefox transitionend.

File: test/transition.js [hunk 3]
```diff
@@ -3,20 +3,15 @@ var transition = require('../src/transition')
...
-  // })
-
   it('should parse duration from node property', () => {
     var el = document.createElement('div');
 
-    el.style[props.duration] = '1.4s'
+    el.style[props.duration] = '2s'
 
-    expect(transition.end._parseDuration(el)).to.equal(1400)
+    expect(transition.end._parseDuration(el)).to.equal(2000)
```
Comment (jquense) [inline test/transition.js]: why change this?

Comment (oliviertassinari) [inline test/transition.js]: > FAILED TESTS:
  Query helpers
    Offset
  Transition helpers
    ✖ should parse duration from node property
      Chrome 53.0.2785 (Mac OS X 10.12.2)
    Error: expected 1000 to equal 1400
        at Assertion.assert (webpack:///~/expect.js/index.js:96:0 <- test.js:2805:14)
        at Assertion.be.Assertion.equal (webpack:///~/expect.js/index.js:216:0 <- test.js:2925:11)
        at Context.<anonymous> (webpack:///test/transition.js:13:49 <- test.js:19252:51)

Comment (oliviertassinari) [inline test/transition.js]: It's green now.

Comment (jquense) [inline test/transition.js]: Generally changing valid inputs on a test case that's failing to make it green isn't the right way the fix the test. The original test should work, If it's failing its an indication that something broke,

Comment (oliviertassinari) [inline test/transition.js]: Digging a bit more, it's coming from
```js
parseFloat('1,4s') === 1
```

Comment (jquense) [inline test/transition.js]: I just ran the test with the original inputs. Nothing seems to be broekn when I run it.

Comment (oliviertassinari) [inline test/transition.js]: > The original test should work, If it's failing its an indication that something broke

Yes, indeed. Do you want me to [skip it](https://github.com/react-bootstrap/dom-helpers/blob/master/test/query.js#L133) ?

Comment (oliviertassinari) [inline test/transition.js]: > I just ran the test with the original inputs. Nothing seems to be broekn when I run it.
 
Ohh, it could by my version of Chrome then. I'm reverting.
(I'm using 53.0.2785.116)

**Comment by jquense** [comment]
thanks!

**Comment by oliviertassinari** [comment]
@jquense Thanks you! Hopefully, I can close https://github.com/oliviertassinari/react-swipeable-views/issues/234 🎉  and [material-ui](https://github.com/callemall/material-ui) is has one less bug.
