### PR TITLE
fix: Fix transitionEnd emulation

### LINKED ISSUE #70: transitionEnd doesn't pass handler through to emulateTransitionEnd
## Describe the bug

`transitionEnd` does not run handler for browsers that do not pass `TRANSITION_END` support check.

## To Reproduce

1. Use transition end in a browser that does not pass `'ontransitionend' in window` or `canUseDOM` check.

## Expected behavior

The handler should still be ran for browsers that do not pass the above check.

## Environment (please complete the following information)

- Operating System: Windows 10
- Browser, Version: IE 11
- React-Bootstrap Version: 1.0.0-beta.11

## Additional context

`TRANSITION_SUPPORTED` variable is always false for IE 11.

### PR DESCRIPTION
**Pull request by taion**
Fixes #70

### CODE REVIEW

File: src/transitionEnd.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ function triggerTransitionEnd(element: HTMLElement) {
   element.dispatchEvent(evt)
 }
 
-export function emulateTransitionEnd(
+function emulateTransitionEnd(
```
Comment (taion) [inline src/transitionEnd.ts]: i didn't see much point exporting this... it's not in the main entry point

File: src/transitionEnd.ts [hunk 2]
```diff
@@ -49,14 +50,15 @@ function transitionEnd(
   handler: Listener,
   duration?: number
 ) {
-  if (!TRANSITION_SUPPORTED) {
-    return emulateTransitionEnd(element, 0, 0)
-  }
```
Comment (taion) [inline src/transitionEnd.ts]: i think we just don't need this? you can still read the transition duration on IE11...

File: src/transitionEnd.ts [hunk 3]
```diff
@@ -49,14 +50,15 @@ function transitionEnd(
...
-
   if (duration == null) duration = parseDuration(element) || 0
-  emulateTransitionEnd(element, duration)
+  const removeEmulate = emulateTransitionEnd(element, duration)
+
+  const remove = listen(element, 'transitionend', handler);
 
-  return listen(element, 'transitionend', handler)
+  return () => {
+    removeEmulate()
```
Comment (taion) [inline src/transitionEnd.ts]: might as well?

**Comment by taion** [comment]
probably can close a few issues in a few places if we ship this
